server:
  port: 8082

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_service_db?user=postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/customer_service_db?user=postgres
    username: postgres
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  cloud:
    openfeign:
      enabled=true:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true